apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 4499
      nodePort: 30080

